### ISSUE TITLE
[Typo] Missing comma in setup.py causes CUDA build failure (v25.06)

### ISSUE THREAD

**Issue by mia1460** [NVIDIA/recsys-examples#88]
Hi,
There is a minor but critical typo in `corelib/dynamicemb/setup.py` in version `v25.06` that causes CUDA extension build to fail.

**Location**:
[[corelib/dynamicemb/setup.py#L101](https://github.com/NVIDIA/recsys-examples/blob/5652241f8e86a1bd939ffeadd7bafdb0c750ef4f/corelib/dynamicemb/setup.py#L101)](https://github.com/NVIDIA/recsys-examples/blob/5652241f8e86a1bd939ffeadd7bafdb0c750ef4f/corelib/dynamicemb/setup.py#L101)

**Problem**:
Two compile flags are concatenated due to a missing comma:

```python
"-U__CUDA_NO_BFLOAT16_CONVERSIONS__"  # ← missing comma here
"-UCUDA_ERROR_CHECK"
```

which leads to:

```bash
... -U__CUDA_NO_BFLOAT16_CONVERSIONS__-UCUDA_ERROR_CHECK ...
```

**Fix**:
Insert a comma between the two flags:

```python
"-U__CUDA_NO_BFLOAT16_CONVERSIONS__",
"-UCUDA_ERROR_CHECK",
```

Thanks for the great work on this project!

**Comment by mia1460** [comment]
Hi @shijieliu, thanks for the quick response!

To reproduce the build failure, I used the following command at tag `v25.06`:

```bash
docker build -f docker/Dockerfile -t recsys-examples:latest .
```

I made two small adjustments before building:

1. In `setup.py`, I commented out the lines:

   ```python
   # "-gencode",
   # "arch=compute_90,code=sm_90",
   ```

2. In the Dockerfile, I replaced the GitHub Megatron-LM clone with a local copy from `third_party/megatron-lm`.

The build failed during CUDA extension compilation due to a joined `nvcc` flag:

```
-U__CUDA_NO_BFLOAT16_CONVERSIONS__-UCUDA_ERROR_CHECK
```
Hope this helps. Let me know if anything else is needed.

**Comment by mia1460** [comment]
Confirmed the typo is fixed in PR https://github.com/NVIDIA/recsys-examples/pull/89. Closing this issue. Thanks for the quick response!
